'use client';
import {useEffect,useState} from 'react'; import {useRouter} from 'next/navigation'; import {supabaseBrowser} from '@/lib/supabase-browser';
export default function Quiz(){const router=useRouter();const [data,setData]=useState<any>(null);const [error,setError]=useState('');const [selected,setSelected]=useState<string>('');const [seconds,setSeconds]=useState(0);const [sending,setSending]=useState(false);
async function load(){const code=sessionStorage.getItem('participant_code');const token=sessionStorage.getItem('participant_session');if(!code||!token){router.replace('/join');return}const r=await fetch('/api/quiz/current',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({participantCode:code,sessionToken:token}),cache:'no-store'});const j=await r.json();if(!r.ok){setError(j.error||'Unable to load quiz');return}setData(j);setSelected(j.answer?.selected_option||'');if(j.status==='COMPLETED'||j.status==='RESULTS_PUBLISHED')router.replace('/completed')}
useEffect(()=>{load();const sb=supabaseBrowser();const c=sb.channel('quiz-state').on('postgres_changes',{event:'*',schema:'public',table:'quiz_state'},()=>load()).subscribe();const t=setInterval(load,3000);return()=>{clearInterval(t);sb.removeChannel(c)}},[]);
useEffect(()=>{const t=setInterval(()=>{if(data?.questionEndsAt)setSeconds(Math.max(0,Math.ceil((new Date(data.questionEndsAt).getTime()-Date.now())/1000)))},250);return()=>clearInterval(t)},[data?.questionEndsAt]);
async function answer(opt:string){if(!data?.question||data.answer||seconds<=0||sending)return;setSelected(opt);setSending(true);setError('');try{const r=await fetch('/api/answer',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({participantCode:sessionStorage.getItem('participant_code'),sessionToken:sessionStorage.getItem('participant_session'),questionId:data.question.id,selectedOption:opt})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Answer failed');await load()}catch(e){setError(e instanceof Error?e.message:'Answer failed')}finally{setSending(false)}}
if(error)return <main className="section"><div className="card" style={{maxWidth:700,margin:'auto'}}><div className="error">{error}</div><button className="btn btn-secondary" onClick={load}>Retry</button></div></main>;
if(!data)return <main className="section"><div className="card center">Loading live quiz…</div></main>;
if(data.status==='PAUSED')return <main className="section"><div className="card center" style={{maxWidth:720,margin:'auto'}}><div className="eyebrow">Quiz paused</div><h1>Please wait.</h1><p className="muted">The organizer has temporarily paused the quiz.</p></div></main>;
if(data.status!=='LIVE'||!data.question)return <main className="section"><div className="card center" style={{maxWidth:720,margin:'auto'}}><div className="eyebrow">Waiting room</div><h1>Quiz hasn’t started yet.</h1><p className="muted">Keep this page open. The live state will update automatically.</p></div></main>;
const q=data.question;return <main className="section"><div className="split"><div><div className="eyebrow">International Service Quiz</div><div className="pill">Question {q.question_number}</div></div><div className="center"><div className="kpi">TIME</div><div className="timer">{seconds}s</div></div></div><div className="card" style={{marginTop:18}}><div className="progress"><span style={{width:`${Math.max(2,(q.question_number/50)*100)}%`}}/></div><div className="question">{q.question_text}</div>{q.image_url&&<img src={q.image_url} alt="Question" style={{maxWidth:'100%',borderRadius:14,marginBottom:18}}/>}<div className="answers">{[['A',q.option_a],['B',q.option_b],['C',q.option_c],['D',q.option_d]].map(([key,text])=><button key={key} className={`answer ${selected===key?'selected':''} ${data.answer?'locked':''}`} disabled={!!data.answer||seconds<=0||sending} onClick={()=>answer(String(key))}><strong>{key}.</strong> {String(text)}</button>)}</div>{data.answer&&<div className="success" style={{marginTop:16}}>Answer submitted. Waiting for the next question…</div>}{seconds===0&&!data.answer&&<div className="notice" style={{marginTop:16}}>Time is up. The next question will start automatically.</div>}</div></main>}
