'use client';
import {useEffect,useState} from 'react';
import {supabaseBrowser} from '@/lib/supabase-browser';
import AdminGuard from '@/components/AdminGuard';
import AdminNav from '@/components/AdminNav';

function Dashboard(){
 const [q,setQ]=useState<any>(null),[state,setState]=useState<any>(null),[questions,setQuestions]=useState<any[]>([]),[count,setCount]=useState(0),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 const sb=supabaseBrowser();
 async function authHeaders(){const {data}=await sb.auth.getSession();if(!data.session)throw new Error('Admin session expired. Please sign in again.');return {authorization:`Bearer ${data.session.access_token}`};}
 async function load(){try{const headers=await authHeaders();const r=await fetch('/api/admin/quiz-control',{headers,cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load quiz.');setQ(j.quiz);setState(j.state);setQuestions(j.questions||[]);setCount(j.participantCount||0)}catch(e){setMsg(e instanceof Error?e.message:'Unable to load quiz.')}}
 useEffect(()=>{load();const t=setInterval(load,3000);return()=>clearInterval(t)},[]);
 async function control(action:string){if(busy)return;setBusy(true);setMsg('');try{const headers={...(await authHeaders()),'content-type':'application/json'};const r=await fetch('/api/admin/quiz-control',{method:'POST',headers,body:JSON.stringify({action})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Quiz control failed.');setMsg(j.message||'Updated.');await load()}catch(e){setMsg(e instanceof Error?e.message:'Quiz control failed.')}finally{setBusy(false)}}
 return <main className="section"><AdminNav/><div className="eyebrow">Organizer dashboard</div><h1>{q?.title||'Quiz'}</h1><div className="stats"><div className="stat"><span className="kpi">STATUS</span><strong>{state?.status||'—'}</strong></div><div className="stat"><span className="kpi">PARTICIPANTS</span><strong>{count}</strong></div><div className="stat"><span className="kpi">QUESTIONS</span><strong>{questions.length}</strong></div></div><div className="actions"><button className="btn btn-secondary" disabled={busy} onClick={()=>control('OPEN_REGISTRATION')}>Open Registration</button><button className="btn btn-secondary" disabled={busy} onClick={()=>control('CLOSE_REGISTRATION')}>Close Registration</button><button className="btn btn-primary" disabled={busy} onClick={()=>control('START')}>Start Quiz</button><button className="btn btn-secondary" disabled={busy} onClick={()=>control('PAUSE')}>Pause</button><button className="btn btn-secondary" disabled={busy} onClick={()=>control('RESUME')}>Resume</button><button className="btn btn-primary" disabled={busy} onClick={()=>control('NEXT')}>Next / Finish</button></div>{msg&&<div className="notice">{msg}</div>}<div className="card" style={{marginTop:20}}><div className="split"><div><h3>Live question</h3><p className="muted">Current: {questions.find(x=>x.id===state?.current_question_id)?.question_number||'—'}</p></div><div className="pill">State: {state?.status||'—'}</div></div><div className="tablewrap"><table className="table"><thead><tr><th>#</th><th>Question</th><th>Points</th><th>Time</th></tr></thead><tbody>{questions.map(x=><tr key={x.id}><td>{x.question_number}</td><td>{x.question_text}</td><td>{x.points}</td><td>{x.time_limit_seconds}s</td></tr>)}</tbody></table></div></div></main>
}
export default function Page(){return <AdminGuard><Dashboard/></AdminGuard>}
